global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "edge-mumbai"
    static_configs:
      - targets: ["edge-mumbai:8081"]

  - job_name: "edge-london"
    static_configs:
      - targets: ["edge-london:8082"]

  - job_name: "edge-nyc"
    static_configs:
      - targets: ["edge-nyc:8083"]